const TIME_INTERVAL_MINS = 5;
const MEDIUM_VOLUME_THRESHOLD = 10;
const HIGH_VOLUME_THRESHOLD = 30;
const CRITICAL_VOLUME_THRESHOLD = 50;

export { TIME_INTERVAL_MINS, MEDIUM_VOLUME_THRESHOLD, HIGH_VOLUME_THRESHOLD, CRITICAL_VOLUME_THRESHOLD }
